-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 29, 2023 at 09:03 AM
-- Server version: 10.4.25-MariaDB
-- PHP Version: 8.1.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `restaurant_website`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` int(11) NOT NULL,
  `product_name` varchar(100) DEFAULT NULL,
  `available_qty` int(11) DEFAULT 0,
  `unit_price` decimal(10,2) DEFAULT NULL,
  `image_url` varchar(255) DEFAULT NULL,
  `details` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `product_name`, `available_qty`, `unit_price`, `image_url`, `details`) VALUES
(2, 'Burger', 25, '249.00', 'images/products/product1.jpg', 'Introducing the extraordinary \"Deluxe Gourmet Burger,\" a culinary marvel that will transport your taste buds to a realm of pure burger bliss. Meticulously crafted with an array of high-quality ingredients, this burger is a symphony of flavors and textures that will leave you craving more.\n<br><br>\nAt the heart of this culinary masterpiece lies a juicy, hand-formed patty made from the finest USDA prime beef, delicately seasoned with a proprietary blend of herbs and spices. Grilled to perfection, each bite bursts with succulent tenderness, showcasing the exceptional quality of the meat.\n<br><br>\nTo elevate the experience further, we layer the patty with a generous slice of aged Gruyère cheese, known for its rich and nutty flavor profile that beautifully complements the beef. As the cheese slowly melts over the patty, it creates a luscious, creamy blanket that envelops every mouthful.\n<br><br>\nNestled between freshly baked artisanal buns, toasted to a golden crispness, our Deluxe Gourmet Burger is adorned with a symphony of vibrant toppings. Crisp lettuce, vine-ripened tomato slices, and thinly sliced red onions add a refreshing crunch, while dill pickles provide a tangy burst of flavor that cuts through the richness.'),
(3, 'Sandwich', 0, '162.31', 'images/products/product2.jpg', 'Introducing our sensational \"Ultimate Deli Sandwich,\" a culinary masterpiece that will redefine your sandwich experience. Expertly crafted with an array of premium ingredients, this sandwich is a symphony of flavors that will leave you craving every bite.\n<br><br>\nAt the core of this extraordinary creation, you\'ll find layers of succulent, thinly sliced roasted turkey breast and savory smoked ham, meticulously seasoned with a blend of herbs and spices. These premium deli meats are a testament to our commitment to quality, ensuring each bite is tender, flavorful, and irresistibly delicious.\n<br><br>\nNestled between slices of freshly baked artisanal bread, with a choice of classic white or wholesome whole grain, our Ultimate Deli Sandwich is elevated with a medley of tantalizing toppings. Crisp lettuce, vine-ripened tomato slices, and thinly sliced red onions add a refreshing crunch, while tangy dill pickles provide a delightful burst of flavor.\n<br><br>\nTo take this sandwich to new heights, we slather on a creamy spread crafted from a secret blend of premium mayonnaise, Dijon mustard, and select herbs and spices. This delectable sauce adds a harmonious balance of tanginess and creaminess, bringing all the flavors together in perfect harmony.'),
(4, 'Lacchi', 50, '392.89', 'images/products/product3.jpg', 'Introducing our delightful \"Creamy Lassi Fusion,\" a refreshingly indulgent drink that combines traditional flavors with a modern twist. This luscious concoction is a harmonious blend of creamy yogurt, aromatic spices, and a burst of fruity goodness, creating a symphony of flavors that will transport you to a state of pure bliss.\n<br><br>\nOur Creamy Lassi Fusion begins with velvety smooth yogurt, handcrafted using the finest quality milk. This yogurt forms the foundation of our drink, providing a rich and creamy base that tantalizes your taste buds with its luxurious texture.\n<br><br>\nTo enhance the experience, we infuse our lassi with a medley of fragrant spices. Cardamom, a touch of saffron, and a hint of aromatic rose water dance together to create a symphony of enticing aromas and flavors. These traditional spices add depth and complexity, elevating the lassi to new heights of deliciousness.'),
(5, 'Chunk', 30, '154.07', 'images/products/product4.jpg', 'Introducing our irresistible \"Crispy Pop Chicken Bites,\" a finger-licking sensation that will have you hooked from the first bite. These bite-sized pieces of pure delight are perfectly seasoned and fried to golden perfection, offering an explosion of flavor and a satisfying crunch in every mouthful.\n<br>\nOur Crispy Pop Chicken Bites start with tender, succulent chicken pieces, carefully selected for their quality and flavor. Each piece is marinated in a secret blend of herbs and spices, ensuring that every bite is infused with a tantalizing burst of savory goodness.\n<br>\nCoated in a light, crispy batter, these delectable chicken bites are fried to achieve an irresistible golden brown crust. The result is a crispy exterior that gives way to juicy, flavorful chicken on the inside, providing a textural contrast that will keep you coming back for more.\n<br>\nBut the magic doesn\'t stop there. To take these bites to a whole new level of taste, we offer a variety of mouthwatering dipping sauces. From tangy barbecue to zesty ranch, or even a spicy buffalo sauce, these accompaniments add an extra dimension of flavor, allowing you to customize your pop chicken experience to perfection.'),
(6, 'Glazed', 24, '291.28', 'images/products/product5.jpg', 'Introducing our delectable \"Glorious Glazed Delights,\" a collection of mouthwatering treats that will satisfy your sweet cravings and leave you wanting more. Indulge in the irresistible allure of our glazed creations, each one carefully crafted to perfection with a luscious, glossy coating that adds a burst of flavor and a touch of elegance.\n<br>\nOur Glorious Glazed Delights feature a variety of delectable options, from fluffy donuts to sumptuous pastries. Each treat is lovingly made with the finest ingredients and baked or fried to achieve a heavenly texture that melts in your mouth.\n<br>\nPrepare to be enchanted by our signature glazes, crafted with precision to create a perfect balance of sweetness and richness. From classic flavors like velvety vanilla and heavenly chocolate to enticing options like zesty lemon or indulgent caramel, our glazes take these treats to a whole new level of deliciousness.'),
(7, 'Jambu Burger', 94, '97.80', 'images/products/product6.jpg', 'Introducing the extraordinary \"Deluxe Gourmet Burger,\" a culinary marvel that will transport your taste buds to a realm of pure burger bliss. Meticulously crafted with an array of high-quality ingredients, this burger is a symphony of flavors and textures that will leave you craving more.\n\nAt the heart of this culinary masterpiece lies a juicy, hand-formed patty made from the finest USDA prime beef, delicately seasoned with a proprietary blend of herbs and spices. Grilled to perfection, each bite bursts with succulent tenderness, showcasing the exceptional quality of the meat.\n\nTo elevate the experience further, we layer the patty with a generous slice of aged Gruyère cheese, known for its rich and nutty flavor profile that beautifully complements the beef. As the cheese slowly melts over the patty, it creates a luscious, creamy blanket that envelops every mouthful.\n\nNestled between freshly baked artisanal buns, toasted to a golden crispness, our Deluxe Gourmet Burger is adorned with a symphony of vibrant toppings. Crisp lettuce, vine-ripened tomato slices, and thinly sliced red onions add a refreshing crunch, while dill pickles provide a tangy burst of flavor that cuts through the richness.'),
(8, 'Gloria Jeans Cofee', 70, '136.61', 'images/products/product7.jpg', 'Introducing our delightful \"Creamy Lassi Fusion,\" a refreshingly indulgent drink that combines traditional flavors with a modern twist. This luscious concoction is a harmonious blend of creamy yogurt, aromatic spices, and a burst of fruity goodness, creating a symphony of flavors that will transport you to a state of pure bliss.\n<br><br>\nOur Creamy Lassi Fusion begins with velvety smooth yogurt, handcrafted using the finest quality milk. This yogurt forms the foundation of our drink, providing a rich and creamy base that tantalizes your taste buds with its luxurious texture.\n<br><br>\nTo enhance the experience, we infuse our lassi with a medley of fragrant spices. Cardamom, a touch of saffron, and a hint of aromatic rose water dance together to create a symphony of enticing aromas and flavors. These traditional spices add depth and complexity, elevating the lassi to new heights of deliciousness.'),
(9, 'Pasta', 85, '365.45', 'images/products/product8.jpg', 'Introducing our delightful \"Creamy Lassi Fusion,\" a refreshingly indulgent drink that combines traditional flavors with a modern twist. This luscious concoction is a harmonious blend of creamy yogurt, aromatic spices, and a burst of fruity goodness, creating a symphony of flavors that will transport you to a state of pure bliss.\n<br><br>\nOur Creamy Lassi Fusion begins with velvety smooth yogurt, handcrafted using the finest quality milk. This yogurt forms the foundation of our drink, providing a rich and creamy base that tantalizes your taste buds with its luxurious texture.\n<br><br>\nTo enhance the experience, we infuse our lassi with a medley of fragrant spices. Cardamom, a touch of saffron, and a hint of aromatic rose water dance together to create a symphony of enticing aromas and flavors. These traditional spices add depth and complexity, elevating the lassi to new heights of deliciousness.'),
(10, 'Cheesy Burger', 93, '314.05', 'images/products/product9.jpg', 'Introducing our delightful \"Creamy Lassi Fusion,\" a refreshingly indulgent drink that combines traditional flavors with a modern twist. This luscious concoction is a harmonious blend of creamy yogurt, aromatic spices, and a burst of fruity goodness, creating a symphony of flavors that will transport you to a state of pure bliss.\n<br><br>\nOur Creamy Lassi Fusion begins with velvety smooth yogurt, handcrafted using the finest quality milk. This yogurt forms the foundation of our drink, providing a rich and creamy base that tantalizes your taste buds with its luxurious texture.\n<br><br>\nTo enhance the experience, we infuse our lassi with a medley of fragrant spices. Cardamom, a touch of saffron, and a hint of aromatic rose water dance together to create a symphony of enticing aromas and flavors. These traditional spices add depth and complexity, elevating the lassi to new heights of deliciousness.'),
(11, 'Beef Bhuna', 12, '427.86', 'images/products/product10.jpg', 'Introducing our delightful \"Creamy Lassi Fusion,\" a refreshingly indulgent drink that combines traditional flavors with a modern twist. This luscious concoction is a harmonious blend of creamy yogurt, aromatic spices, and a burst of fruity goodness, creating a symphony of flavors that will transport you to a state of pure bliss.\n<br><br>\nOur Creamy Lassi Fusion begins with velvety smooth yogurt, handcrafted using the finest quality milk. This yogurt forms the foundation of our drink, providing a rich and creamy base that tantalizes your taste buds with its luxurious texture.\n<br><br>\nTo enhance the experience, we infuse our lassi with a medley of fragrant spices. Cardamom, a touch of saffron, and a hint of aromatic rose water dance together to create a symphony of enticing aromas and flavors. These traditional spices add depth and complexity, elevating the lassi to new heights of deliciousness.'),
(12, 'Pan Cake', 83, '352.86', 'images/products/product11.jpg', 'Introducing our delightful \"Creamy Lassi Fusion,\" a refreshingly indulgent drink that combines traditional flavors with a modern twist. This luscious concoction is a harmonious blend of creamy yogurt, aromatic spices, and a burst of fruity goodness, creating a symphony of flavors that will transport you to a state of pure bliss.\n<br><br>\nOur Creamy Lassi Fusion begins with velvety smooth yogurt, handcrafted using the finest quality milk. This yogurt forms the foundation of our drink, providing a rich and creamy base that tantalizes your taste buds with its luxurious texture.\n<br><br>\nTo enhance the experience, we infuse our lassi with a medley of fragrant spices. Cardamom, a touch of saffron, and a hint of aromatic rose water dance together to create a symphony of enticing aromas and flavors. These traditional spices add depth and complexity, elevating the lassi to new heights of deliciousness.'),
(13, 'Honey Cake', 84, '153.72', 'images/products/product12.jpg', 'Introducing our delightful \"Creamy Lassi Fusion,\" a refreshingly indulgent drink that combines traditional flavors with a modern twist. This luscious concoction is a harmonious blend of creamy yogurt, aromatic spices, and a burst of fruity goodness, creating a symphony of flavors that will transport you to a state of pure bliss.\n<br><br>\nOur Creamy Lassi Fusion begins with velvety smooth yogurt, handcrafted using the finest quality milk. This yogurt forms the foundation of our drink, providing a rich and creamy base that tantalizes your taste buds with its luxurious texture.\n<br><br>\nTo enhance the experience, we infuse our lassi with a medley of fragrant spices. Cardamom, a touch of saffron, and a hint of aromatic rose water dance together to create a symphony of enticing aromas and flavors. These traditional spices add depth and complexity, elevating the lassi to new heights of deliciousness.'),
(14, 'Chiken Toast', 60, '194.81', 'images/products/product13.jpg', 'Introducing our delightful \"Creamy Lassi Fusion,\" a refreshingly indulgent drink that combines traditional flavors with a modern twist. This luscious concoction is a harmonious blend of creamy yogurt, aromatic spices, and a burst of fruity goodness, creating a symphony of flavors that will transport you to a state of pure bliss.\n<br><br>\nOur Creamy Lassi Fusion begins with velvety smooth yogurt, handcrafted using the finest quality milk. This yogurt forms the foundation of our drink, providing a rich and creamy base that tantalizes your taste buds with its luxurious texture.\n<br><br>\nTo enhance the experience, we infuse our lassi with a medley of fragrant spices. Cardamom, a touch of saffron, and a hint of aromatic rose water dance together to create a symphony of enticing aromas and flavors. These traditional spices add depth and complexity, elevating the lassi to new heights of deliciousness.'),
(15, 'Pizza Medium', 80, '67.90', 'images/products/product14.jpg', 'Introducing our delightful \"Creamy Lassi Fusion,\" a refreshingly indulgent drink that combines traditional flavors with a modern twist. This luscious concoction is a harmonious blend of creamy yogurt, aromatic spices, and a burst of fruity goodness, creating a symphony of flavors that will transport you to a state of pure bliss.\n<br><br>\nOur Creamy Lassi Fusion begins with velvety smooth yogurt, handcrafted using the finest quality milk. This yogurt forms the foundation of our drink, providing a rich and creamy base that tantalizes your taste buds with its luxurious texture.\n<br><br>\nTo enhance the experience, we infuse our lassi with a medley of fragrant spices. Cardamom, a touch of saffron, and a hint of aromatic rose water dance together to create a symphony of enticing aromas and flavors. These traditional spices add depth and complexity, elevating the lassi to new heights of deliciousness.'),
(16, 'Noodles', 79, '436.84', 'images/products/product15.jpg', 'Introducing our delightful \"Creamy Lassi Fusion,\" a refreshingly indulgent drink that combines traditional flavors with a modern twist. This luscious concoction is a harmonious blend of creamy yogurt, aromatic spices, and a burst of fruity goodness, creating a symphony of flavors that will transport you to a state of pure bliss.\n<br><br>\nOur Creamy Lassi Fusion begins with velvety smooth yogurt, handcrafted using the finest quality milk. This yogurt forms the foundation of our drink, providing a rich and creamy base that tantalizes your taste buds with its luxurious texture.\n<br><br>\nTo enhance the experience, we infuse our lassi with a medley of fragrant spices. Cardamom, a touch of saffron, and a hint of aromatic rose water dance together to create a symphony of enticing aromas and flavors. These traditional spices add depth and complexity, elevating the lassi to new heights of deliciousness.'),
(17, 'Biriyani', 91, '488.87', 'images/products/product16.jpg', 'Introducing our delightful \"Creamy Lassi Fusion,\" a refreshingly indulgent drink that combines traditional flavors with a modern twist. This luscious concoction is a harmonious blend of creamy yogurt, aromatic spices, and a burst of fruity goodness, creating a symphony of flavors that will transport you to a state of pure bliss.\n<br><br>\nOur Creamy Lassi Fusion begins with velvety smooth yogurt, handcrafted using the finest quality milk. This yogurt forms the foundation of our drink, providing a rich and creamy base that tantalizes your taste buds with its luxurious texture.\n<br><br>\nTo enhance the experience, we infuse our lassi with a medley of fragrant spices. Cardamom, a touch of saffron, and a hint of aromatic rose water dance together to create a symphony of enticing aromas and flavors. These traditional spices add depth and complexity, elevating the lassi to new heights of deliciousness.');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `product_name` (`product_name`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=22;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
